"""Persistence contracts. Services depend on these, never on psycopg directly."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol

from jobbot.domain.models import FeedbackAction, Job, Profile, User


class UserRepository(Protocol):
    def get(self, chat_id: int) -> User | None: ...
    def list_active(self) -> list[User]: ...
    def list_all(self) -> list[User]: ...
    def upsert(self, user: User) -> None: ...
    def delete(self, chat_id: int) -> None: ...


class InviteRepository(Protocol):
    def create(self, code: str, created_by: int, max_uses: int, expires_at: datetime | None) -> None: ...


class ProfileRepository(Protocol):
    def get(self, chat_id: int) -> Profile | None: ...
    def get_cv_file_id(self, chat_id: int) -> str | None: ...
    def get_cv_text(self, chat_id: int) -> str | None: ...
    def list_with_cv(self) -> list[int]:
        """Chat ids that have stored CV text (for re-parsing everyone)."""
        ...

    def save(self, chat_id: int, profile: Profile, cv_text: str | None = None) -> None: ...


class JobRepository(Protocol):
    def upsert_many(self, jobs: list[Job], embeddings: dict[str, list[float]]) -> None: ...
    def get_embeddings(self, job_ids: list[str]) -> dict[str, list[float]]: ...
    def prune(self, older_than_days: int) -> int: ...


class SentRepository(Protocol):
    def sent_keys(self, chat_id: int) -> tuple[set[str], set[str]]:
        """Return (job_ids, dedupe_keys) already sent to this user."""
        ...

    def record(self, chat_id: int, jobs: list[tuple[Job, float]]) -> None: ...
    def prune(self, older_than_days: int) -> int: ...


class FeedbackRepository(Protocol):
    def job_ids_by_action(self, chat_id: int) -> dict[FeedbackAction, list[str]]: ...


class RunRepository(Protocol):
    def start(self, slot: str) -> int: ...
    def finish(self, run_id: int, status: str, stats: dict[str, Any], error: str | None) -> None: ...
    def delivered_since(self, slot: str, since: datetime) -> bool:
        """True if a real (non-dry) run of this slot finished ok/partial at or after `since`."""
        ...
