"""Vocabulary used by the heuristic (no-LLM) CV parser."""

SKILLS = [
    # Languages
    "Python",
    "JavaScript",
    "TypeScript",
    "Java",
    "Kotlin",
    "Swift",
    "Go",
    "Golang",
    "Rust",
    "C",
    "C++",
    "C#",
    "PHP",
    "Ruby",
    "Scala",
    "R",
    "Dart",
    "SQL",
    "Bash",
    "Elixir",
    # Web / backend
    "Django",
    "DRF",
    "Django REST Framework",
    "Flask",
    "FastAPI",
    "Node.js",
    "Express",
    "NestJS",
    "Spring",
    "Spring Boot",
    "Laravel",
    "Rails",
    "ASP.NET",
    ".NET",
    "GraphQL",
    "REST",
    "gRPC",
    "Celery",
    "RabbitMQ",
    "Kafka",
    "Redis",
    "Microservices",
    # Frontend / mobile
    "React",
    "Next.js",
    "Vue",
    "Nuxt",
    "Angular",
    "Svelte",
    "HTML",
    "CSS",
    "Tailwind",
    "Redux",
    "Flutter",
    "React Native",
    "Android",
    "iOS",
    # Data / ML
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "SQLite",
    "Elasticsearch",
    "DynamoDB",
    "BigQuery",
    "Snowflake",
    "Pandas",
    "NumPy",
    "scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Spark",
    "Airflow",
    "dbt",
    "Tableau",
    "Power BI",
    "Excel",
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "LLM",
    "Data Analysis",
    "Data Engineering",
    "Statistics",
    # Infra / DevOps
    "Docker",
    "Kubernetes",
    "Terraform",
    "Ansible",
    "AWS",
    "GCP",
    "Azure",
    "Linux",
    "Nginx",
    "CI/CD",
    "GitHub Actions",
    "Jenkins",
    "Prometheus",
    "Grafana",
    "Git",
    # Product / design / other
    "Figma",
    # Design
    "Photoshop",
    "Illustrator",
    "InDesign",
    "CorelDRAW",
    "Canva",
    "After Effects",
    "Premiere Pro",
    "CapCut",
    "Blender",
    "Branding",
    "Logo Design",
    "Motion Graphics",
    "Typography",
    # Virtual assistance / admin
    "Google Workspace",
    "Microsoft Office",
    "Calendar Management",
    "Email Management",
    "Data Entry",
    "Transcription",
    "Zendesk",
    "HubSpot",
    "Notion",
    "Trello",
    "Asana",
    "Slack",
    # Content
    "Content Strategy",
    "Social Media Management",
    "Video Editing",
    "WordPress",
    "Content Creation",
    "Email Marketing",
    "Community Management",
    "UI/UX",
    "Agile",
    "Scrum",
    "Jira",
    "Product Management",
    "Project Management",
    "SEO",
    "Content Writing",
    "Copywriting",
    "Digital Marketing",
    "Social Media",
    "Customer Support",
    "Sales",
    "Accounting",
    "Financial Analysis",
    "QuickBooks",
    "Human Resources",
    "Recruitment",
    "Testing",
    "QA",
    "Selenium",
    "Cypress",
    "Pytest",
    "Security",
    "Penetration Testing",
    "Blockchain",
    "Solidity",
]

TITLE_WORDS = [
    "assistant",
    "creator",
    "editor",
    "copywriter",
    "va",
    "engineer",
    "developer",
    "programmer",
    "architect",
    "analyst",
    "scientist",
    "designer",
    "manager",
    "consultant",
    "specialist",
    "administrator",
    "officer",
    "lead",
    "writer",
    "accountant",
    "marketer",
    "strategist",
    "coordinator",
    "executive",
    "representative",
]

SENIORITY_WORDS = {
    "intern": "intern",
    "junior": "junior",
    "graduate": "junior",
    "entry": "junior",
    "mid": "mid",
    "intermediate": "mid",
    "senior": "senior",
    "sr": "senior",
    "lead": "lead",
    "principal": "lead",
    "staff": "lead",
    "head": "lead",
    "director": "lead",
}
